trigger: none
pr: none

# Schedule: Run every 1 hour
schedules:
  - cron: "0 */1 * * *"  # Every 1 hour at minute 0
    displayName: "Run tests every 1 hour"
    branches:
      include:
        - sv2-long-running-pipeline
    always: true  # Run even if there are no code changes

parameters:
  - name: subscriptionId
    displayName: "Azure Subscription ID"
    type: string
    default: "37deca37-c375-4a14-b90a-043849bd2bf1"

  - name: serviceConnection
    displayName: "Azure Service Connection"
    type: string
    default: "Azure Container Networking - Standalone Test Service Connection"

  - name: location
    displayName: "Deployment Region"
    type: string
    default: "centraluseuap"

  - name: runSetupStages
    displayName: "Create New Infrastructure Setup"
    type: boolean
    default: false

  # Setup-only parameters (only used when runSetupStages=true)
  - name: resourceGroupName
    displayName: "Resource Group Name used when runSetupStages is true"
    type: string
    default: "sv2-long-run-$(Build.BuildId)"

  - name: vmSkuDefault
    displayName: "VM SKU for Default Node Pool used when runSetupStages is true"
    type: string
    default: "Standard_D4s_v3"

  - name: vmSkuHighNIC
    displayName: "VM SKU for additional Node Pool used when runSetupStages is true"
    type: string
    default: "Standard_D16s_v3"

extends:
  template: template/long-running-pipeline-template.yaml
  parameters:
    subscriptionId: ${{ parameters.subscriptionId }}
    location: ${{ parameters.location }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
    vmSkuDefault: ${{ parameters.vmSkuDefault }}
    vmSkuHighNIC: ${{ parameters.vmSkuHighNIC }}
    serviceConnection: ${{ parameters.serviceConnection }}
    runSetupStages: ${{ parameters.runSetupStages }}
